spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=TPO;trustServerCertificate=true
    username: sa
    password: asdP929klks
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: task_manager